### ISSUE TITLE
check_users not correctly detecting thresholds

### ISSUE THREAD

**Issue by box293** [nagios-plugins/nagios-plugins#81] opened 2015-04-15 00:23 UTC
```
check_users -V
check_users v2.0.3 (nagios-plugins 2.0.3)
```

With 1 user logged in:

```
check_users -w 1 -c 2
USERS OK - 1 users currently logged in |users=1;1;2;0

echo $?
0
```

This should have been a WARNING.

With 2 users logged in:

```
/check_users -w 1 -c 2
USERS WARNING - 2 users currently logged in |users=2;1;2;0

echo $?
1
```

This should have been CRITICAL not WARNING

**Comment by tmcnag** [comment] 2015-05-06 18:21
This is technically working as intended according to the plugins docs:

https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

From the examples:

>Command line
>`check_stuff -w10 -c20`
>
>Meaning
>Critical if "stuff" is over 20, else warn if over 10 (will be critical if "stuff" is less than 0)

The thresholds by default need to be greater-than, not greater-than-or-equal.  Maybe not expected or necessarily intuitive, but this is documented.  The way it was explained to me is to think of it as a glass of water.  If it can hold 100mL, then 100mL would not be too much.  101mL would cause an issue.  In the same way, a threshold of 1 in your example would not be a warning, however a threshold of 0 would be.

I believe `./check_users -w @1: -c @2:` *should* be correct as per the docs, but the plugin does not seem to be able to handle that syntax:

`$ ./check_users -w @1: -c @2:`
`check_users: Warning threshold must be a positive integer`
`Usage:`
`check_users -w <users> -c <users>`

**Comment by box293** [comment] 2015-05-08 04:15
I understand what you are saying about the thresholds, but I am glad we have inadvertently unidentified another bug.

**Comment by tmcnag** [comment] 2015-07-27 20:01
Labeling as enhancement.  I cannot find any official documentation that says a plugin *must* respect the range thresholds, so I cannot call this a bug.

**Comment by jfrickson** [comment] 2016-11-07 19:10
Since it didn't recognize things like `@`, I'm calling it a bug. (Sorry @tmcnag :)

check_users now uses the standard warning and critical ranges parser and a standard perdata output routine. Fixed in 'maint' branch via commit https://github.com/nagios-plugins/nagios-plugins/commit/972ee5bc7286b2ed7c7774e09f35bddeb1d05189

**Closed by jfrickson** 2016-11-07 19:10 UTC
Labels: enhancement
