### ISSUE TITLE
check_http v2.2.1.6.g4103 > Socket timeout

### ISSUE THREAD

**Issue by BenoitPoulet** [nagios-plugins/nagios-plugins#311] opened 2017-08-11 07:39 UTC
Hello,

I have a lot of false timeout since i upgrade from 2.1.4 to 2.2.1

For the same URL with same parameters, 2.1.4 works fine, but 2.2.1 de timeout.

I did the last check with the following Git checkout : check_http v2.2.1.6.g4103 (nagios-plugins 2.2.1)

Regards.

Traces :

]./check_http  -S -f follow -H 10.74.0.159 -p 443 -t 30 -u / --verbose
SSL initialized
GET / HTTP/1.1
User-Agent: check_http/v2.2.1.6.g4103 (nagios-plugins 2.2.1)
Connection: close
Host: 10.74.0.159
Accept: */*

https://10.74.0.159:443/ is 207 characters
STATUS: HTTP/1.1 302 Moved Temporarily
CRITICAL - Socket timeout

######################################################################

$ ./check_http  -S -f follow -H 10.74.0.159 -p 443 -t 30 -u / --verbose
SSL initialized
GET / HTTP/1.1
User-Agent: check_http/v2.1.4 (nagios-plugins 2.1.4)
Connection: close
Host: 10.74.0.159
Accept: */*

https://10.74.0.159:443/ is 207 characters
STATUS: HTTP/1.1 302 Moved Temporarily
**** HEADER ****
Date: Wed, 14 Oct 1970 21:47:20 GMT
Server: Mbedthis-Appweb/2.4.2
ETag: "550-42f1-44f54"
Content-length: 0
Connection: close
Location: https://10.74.0.159/login.html

**** CONTENT ****

Redirection vers https://10.74.0.159:443/login.html
SSL initialized
GET /login.html HTTP/1.1
User-Agent: check_http/v2.1.4 (nagios-plugins 2.1.4)
Connection: close
Host: 10.74.0.159
Accept: */*

https://10.74.0.159:443/login.html is 16738 characters
STATUS: HTTP/1.1 200 OK
**** HEADER ****
Date: Wed, 14 Oct 1970 21:47:21 GMT
Server: Mbedthis-Appweb/2.4.2
Cache-Control: no-cache
Content-type: text/html
ETag: "550-42f1-44f54"
Content-length: 16535
Connection: close

**** CONTENT ****
  var userNamePrintableMsg   = "The Username must contain only printable characters and no white space.";  // The Username must contai  var passwordPrintableMsg   = "The Password must contain only printable characters and no white space.";  // The Password must contai  var loginFailedVerifyMsg   = "Login failed. Verify that your username and password are correct.";  // Login failed. Verify that your  var loginSessionCtExceeded = "The maximum number of user sessions is reached.";  // The maximum number of user sessions has been rea  var loginForbiddenMsg      = "Login forbidden. A GUI session has been created and is active. You can not login again from another ta  var loginFailedPrvMsg      = "Login failed. User does not have 'Login to Dell BMC' privilege.";     // Login failed. User does not h  var fwUpdateSysNotAvailMsg = "Firmware Update is in progress. System is not available now. Please try again later!";          // Fir                        <td align="center" valign="middle"><a onfocus="style.textDecoration = 'underline';" onblur="style.textDecorati                        <td align="center" valign="middle" width="6"><a onfocus="style.textDecoration = 'underline';" onblur="style.te                        <td align="center" valign="middle" width="6"><a onfocus="style.textDecoration = 'underline';" onblur="style.te                                  <a onfocus="style.textDecoration = 'underline';" onblur="style.textDecoration = 'none';" class="butt                                  <a onfocus="style.textDecoration = 'underline';" onblur="style.textDecoration = 'none';" class="butt</html>y>ipt>lockElement('loginStatus');atus").innerHTML = fwUpdateSysNotAvailMsg;pan></a>
HTTP OK: HTTP/1.1 200 OK - 16738 octets en 1,460 secondes de temps de réponse |time=1,459660s;;;0,000000 size=16738B;;;0

**Comment by hedenface** [comment] 2017-09-16 20:56
I am unable to reproduce the issue on my end with the current `maint` branch or release.

What operating system are you on? Can I see the failing timeout wrapped in a `time` command please?

**Comment by BenoitPoulet** [comment] 2017-09-19 09:08
Hello,

I did all the tests with the master branch.

**OS  : CentOS release 6.9 (Final)**

The test with `time` command :
/home/nagios-plugins $ time ./plugins/check_http -S -f follow -H 10.74.0.159 -p 443 -t 30 -u / --verbose
SSL initialized
GET / HTTP/1.1
User-Agent: check_http/v2.2.1.6.g4103 (nagios-plugins 2.2.1)
Connection: close
Host: 10.74.0.159
Accept: */*


https://10.74.0.159:443/ is 207 characters
STATUS: HTTP/1.1 302 Moved Temporarily
CRITICAL - Socket timeout

real    0m30.002s
user    0m27.602s
sys     0m0.016s

#####################################################

**OS : CentOS Linux release 7.3.1611 (Core)**

time  ./plugins/check_http -S -f follow -H 10.74.0.159 -p 443 -t 30 -u / --verbose
SSL initialized
GET / HTTP/1.1
User-Agent: check_http/v2.2.1.6.g4103 (nagios-plugins 2.2.1)
Connection: close
Host: 10.74.0.159
Accept: */*


https://10.74.0.159:443/ is 207 characters
STATUS: HTTP/1.1 302 Moved Temporarily
CRITICAL - Socket timeout

real    0m30.003s
user    0m29.108s
sys     0m0.004s

######################################

But after reading your response i saw that you are using the "maint" branch.
So i did the tests again, with the "maint" branch and the problem is gone.

What is the meaning of this branch compared to the master ?

**Comment by hedenface** [comment] 2017-09-19 13:05
`maint` is the upcoming release. In this case, staging for 2.2.1 and 2.3.0. I'm gonna close the issue, as it looks like this is resolved. :)

If you have any further issues, re-open or post a new one. Thanks!

**Closed by hedenface** 2017-09-19 13:05 UTC
