### ISSUE TITLE
Mac OS X check_load error

### ISSUE THREAD

**Issue by stetner** [nagios-plugins/nagios-plugins#430] opened 2018-12-28 11:12 UTC
Mac os x does not separate load averages with commas in the uptime output.

This line in "plugins/check_load.c" line 160 of 342

﻿﻿sscanf (input_buffer, "%*[^l]load averages: %lf, %lf, %lf", &la1, &la5, &la15);

will not scan the output correctly, this will:

sscanf (input_buffer, "%*[^l]load averages: %lf %lf %lf", &la1, &la5, &la15);

Cheers,
Doug

**Comment by sawolf** [comment] 2019-10-04 16:21
Hi Doug,

This should be fixed if you compile from `maint`. I don't have access to a Mac right now, but if the issue isn't resolved for you, let me know and I'll reopen this issue.

**Closed by sawolf** 2019-10-04 16:21 UTC
Labels: Bug
