### ISSUE TITLE
check_disk - Behavior change remote_fs

### ISSUE THREAD

**Issue by martin-par** [nagios-plugins/nagios-plugins#491] opened 2019-10-21 11:48 UTC
After https://github.com/nagios-plugins/nagios-plugins/issues/455 behavior changed.

Before the code change:
 "-L" checks only local filesystems against thresholds and also check if remote_fs is staled

After:
"-L" also checks remote filesystems against thresholds

Before
`DISK OK - free space: / 17228 MiB (90.64% inode=96%); /boot 234 MiB (67.93% inode=100%); /home 4644 MiB (99.77% inode=100%); /opt/work 94077 MiB (98.46% inode=100%); /var 16874 MiB (88.78% inode=99%);| /=1777MiB;16024;18027;0;20030 /boot=110MiB;290;326;0;363 /home=10MiB;3928;4419;0;4911 /opt/work=1467MiB;80532;90598;0;100665 /var=2132MiB;16024;18027;0;20030`

After
`DISK OK - free space: / 17228 MiB (90.64% inode=96%); /boot 234 MiB (67.93% inode=100%); /home 4644 MiB (99.77% inode=100%); /opt/work 94077 MiB (98.46% inode=100%); /var 16873 MiB (88.77% inode=99%); /opt/work/shared/blobs 10137 MiB (52.78% inode=93%); /opt/work/shared/content-images 38761 MiB (80.61% inode=94%); /opt/work/shared/layers 4511 MiB (98.59% inode=100%); /opt/work/shared/options 4507 MiB (98.50% inode=100%); /opt/work/shared/resource 4509 MiB (98.56% inode=100%); /opt/work/shared/published 8299 MiB (88.20% inode=63%); /opt/work/www 226872 MiB (93.96% inode=99%); /opt/work/shared/apps 9287 MiB (98.70% inode=100%); /opt/work/shared/location 9291 MiB (98.74% inode=100%);| /=1777MiB;16024;18027;0;20030 /boot=110MiB;290;326;0;363 /home=10MiB;3928;4419;0;4911 /opt/work=1467MiB;80532;90598;0;100665 /var=2132MiB;16024;18027;0;20030 /opt/work/shared/blobs=9069MiB;16024;18027;0;20030 /opt/work/shared/content-images=9320MiB;40112;45126;0;50140 /opt/work/shared/layers=64MiB;3826;4304;0;4783 /opt/work/shared/options=68MiB;3826;4304;0;4783 /opt/work/shared/resource=65MiB;3826;4304;0;4783 /opt/work/shared/published=1110MiB;7858;8840;0;9823 /opt/work/www=14574MiB;201381;226554;0;251727 /opt/work/shared/apps=121MiB;7858;8840;0;9823 /opt/work/shared/location=118MiB;7858;8840;0;9823`

**Comment by sawolf** [comment] 2019-10-21 15:39
Thanks for pointing this out. I don't think I was careful enough when implementing the change for #455 - the plugin's own documentation states that this was working as intended before.

Either way, it should be fixed in `maint` now.

**Closed** 2019-12-04 20:02 UTC
