### ISSUE TITLE
http_check returning critical after upgrade to v2.2.1

### ISSUE THREAD

**Issue by cbj111** [nagios-plugins/nagios-plugins#416] opened 2018-09-14 01:43 UTC
I'm checking that an application server is alive and am expecting it to return "HTTP/1.0 415 Request data not in text/xml format" when I feed it an empty request so I am calling check_http with these arguments:

check_http -v -H x.x.x.x -p 8412 -P "POST AppInterfaceServerRequest HTTP/1.0\nContent-Type: text/xml" -e "415" -w 5 -c 10

This used to work in v2.0.3 but as soon as I upgraded to v2.2.1 it returned the following error:

```
[root@nagiosxi libexec]# ./check_http -v -H x.x.x.x -p 8412 -P "POST AppInterfaceServerRequest HTTP/1.0\nContent-Type: text/xml" -e "415" -w 5 -c 10
POST / HTTP/1.1
User-Agent: check_http/v2.2.1 (nagios-plugins 2.2.1)
Connection: close
Host: x.x.x.x:8412
Accept: */*
Content-Type: application/x-www-form-urlencoded
Content-Length: 63

POST AppInterfaceServerRequest HTTP/1.0\nContent-Type: text/xml

http://x.x.x.x:8412/ is 229 characters
STATUS: HTTP/1.0  415 Request data not in text/xml format
**** HEADER ****
Date 2018-09-10 17:43:02.671
Server: RedBack Application Server 5.1
MIME-version: 1.0
Last-modified: 2018-09-10 17:43:02.671
Content-type: text/plain
Content-length: 180
**** CONTENT ****

Status line output matched "415" - 
HTTP CRITICAL: Invalid Status Line (HTTP/1.0  415 Request data not in text/xml format)
[root@nagiosxi libexec]#
```

The status returns 415 and check_http reports a match but it then returns a CRITICAL response.

**Comment by Madlohe** [comment] 2019-08-01 18:02
The only thing that stands out to me here is the status line: I see two spaces between the protocol version and the status code. The plugin seems to only handle one space. The same code is present in v2.0.3, so this may not be the cause.

I've pushed a commit into the "maint" branch which would allow for multiple spaces. Would you be willing to compile from there and see whether this resolves your issue?

**Comment by sawolf** [comment] 2019-09-19 20:06
Closing this -- if you still have issues after compiling from maint, let me know and I can re-open.

**Closed by sawolf** 2019-09-19 20:06 UTC
Labels: Bug
