### ISSUE TITLE
check_dig uppercase problems

### ISSUE THREAD

**Issue by ch82** [nagios-plugins/nagios-plugins#114] opened 2015-10-13 07:00 UTC
Since some time google.ru began to return itself as GOOGLE.ru to dig command.
So testing external dns resolving by check_dig -H server -l google.ru leads to warning.
# ./check_dig -H server -l google.ru -v

/usr/bin/dig   -p 53 @server google.ru A +tries=3 +time=4
Looking for: 'google.ru'
;; ANSWER SECTION:
GOOGLE.ru.              18      IN      A       173.194.122.239
GOOGLE.ru.              18      IN      A       173.194.122.255
GOOGLE.ru.              18      IN      A       173.194.122.247
GOOGLE.ru.              18      IN      A       173.194.122.248

;; AUTHORITY SECTION:
GOOGLE.ru.              188446  IN      NS      ns1.google.com.
GOOGLE.ru.              188446  IN      NS      ns3.google.com.
GOOGLE.ru.              188446  IN      NS      ns4.google.com.
GOOGLE.ru.              188446  IN      NS      ns2.google.com.

;; ADDITIONAL SECTION:
ns1.google.com.         187872  IN      A       216.239.32.10
ns2.google.com.         187872  IN      A       216.239.34.10
ns3.google.com.         187872  IN      A       216.239.36.10
ns4.google.com.         187872  IN      A       216.239.38.10

;; Query time: 1 msec
;; SERVER: ?.?.?.?#53(?.?.?.?)
;; WHEN: Tue Oct 13 09:58:22 MSK 2015
;; MSG SIZE  rcvd: 255

DNS WARNING - 0.014 seconds response time (Server not found in ANSWER SECTION)|time=0.013566s;;;0.000000

**Comment by waja** [comment] 2015-10-13 07:13
Looks like a duplicate of https://github.com/monitoring-plugins/monitoring-plugins/issues/1233

**Comment by jfrickson** [comment] 2016-10-31 20:22
This issue has been resolved

**Closed by jfrickson** 2016-10-31 20:22 UTC
